eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8100
spring:
  application:
    name: departments
    #    we don't need the import because it is already in the config server.
  #  config:
  #    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5433/departments
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#config that allows feign-client to call student-service
application:
  config:
    student-url: http://localhost:8222/api/students